name: shell commands
on:
- push
env:
  ACCESS_KEY: ${{ secrets.ACCESS_KEY}}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY}}
jobs:
  terraform-workflow:
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v1
    - name: Set Terraform
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: 1.1.9
    - name: Terraform init
      run: terraform init

    - name: Terraform plan
      run: terraform plan
    - name: terraform apply
      run: terraform apply --auto-approve
    - name: Test
      run: ls
    - name: Copy a file
      run: "mkdir ik \ntouch bk.txt \n#magic___^_^___line\n#magic___^_^___line\n#magic___^_^___line\n#magic___^_^___line\n#magic___^_^___line\n"
